---
title: The Graphic Literature Guild
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: graphicliteratureguild@gmail.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: ''
url: http://glgcomics.org
twitter_username: glgcomics
github_username: glgcomics
facebook_username: glgcomics
instagram_username: glgcomics
markdown: kramdown
exclude:
- bower_components
- bower.json
- node_modules
- package.json
- Gruntfile.coffee
- Rakefile
include:
- ".nojekyll"
