title: The Graphic Literature Guild
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://glgcomics.org # need to update this to https
twitter_username: glgcomics
twitter:
  username: glgcomics
github_username:  glgcomics
facebook_username: glgcomics
facebook:
  publisher: glgcomics
instagram_username: glgcomics

# Build settings
markdown: kramdown
theme: minima
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

permalink: "/blog/:title/"
paginate: 5
paginate_path: "/blog/:num/"
